export const EVENTS = {
  JOIN: 'join',
  CREATE_CHARACTER: 'createCharacter',
  DELETE_CHARACTER: 'deleteCharacter',
  CHARACTER_CREATED: 'characterCreated',
  CHARACTERS_CHANGED: 'charactersChanged',
  MOVE: 'move',
  AIM: 'aim',
  ATTACK: 'attack',
  PICKUP: 'pickup',
  EQUIP: 'equip',
  UNEQUIP: 'unequip',
  DESTROY_ITEM: 'destroyItem',
  ALLOCATE_STAT: 'allocateStat',
  USE_SKILL: 'useSkill',
  USE_CONSUMABLE: 'useConsumable',
  RESPAWN: 'respawn',
  USE_PORTAL: 'usePortal',
  CAST_TOWN_RECALL: 'castTownRecall',
  NPC_INTERACT: 'npcInteract',
  QUEST_ACCEPT: 'questAccept',
  QUEST_TURN_IN: 'questTurnIn',
  WORLD_STATE: 'worldState',
  ERROR: 'error',
  CHAT_SEND: 'chatSend',
  CHAT_MESSAGE: 'chatMessage',
  PARTY_INVITE: 'partyInvite',
  PARTY_ACCEPT: 'partyAccept',
  PARTY_DECLINE: 'partyDecline',
  PARTY_LEAVE: 'partyLeave',
  PARTY_STATE: 'partyState',
  ONLINE_PLAYERS: 'onlinePlayers',
  SESSION_END: 'sessionEnd',
  VENDOR_OPEN: 'vendorOpen',
  VENDOR_CATALOG: 'vendorCatalog',
  VENDOR_BUY: 'vendorBuy',
  VENDOR_SELL: 'vendorSell',
  TRADE_REQUEST: 'tradeRequest',
  TRADE_ACCEPT: 'tradeAccept',
  TRADE_DECLINE: 'tradeDecline',
  TRADE_CANCEL: 'tradeCancel',
  TRADE_UPDATE: 'tradeUpdate',
  TRADE_READY: 'tradeReady',
  TRADE_STATE: 'tradeState',
};

export const CURSOR_MODE = {
  DEFAULT: 'default',
  MOVE: 'move',
  ATTACK: 'attack',
  LOOT: 'loot',
  PORTAL: 'portal',
  TALK: 'talk',
  VENDOR: 'vendor',
};
